name: docker
on:
  push:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      - run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t minionflo/ip_api .
      - run: docker push minionflo/ip_api