name: docker
on:
  push:
    branches: [ master ]

jobs:
  build_push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go build main.go
      - run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t minionflo/ip_api .
      - run: docker push minionflo/ip_api